version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.1.0
  heroku: circleci/heroku@0.0.10 # Invoke the Heroku orb

jobs:
  npm-install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install

workflows:
  test-app-and-deploy: 
    jobs:
      steps:
      - checkout
      - cypress/run
      - deploy-via-git
      - npm-install

