version: 2.1
orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1.29.0
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deploy:
    jobs:
      - node/test:
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
          version: '16.10'
          # If you are using yarn, change the line below from "npm" to "yarn"
          pkg-manager: npm

      - cypress/install:
          build: 'npm run build' # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          # record: true # record results on Cypress Dashboard
          parallel: true # split all specs across machines
          parallelism: 4 # use 4 CircleCI machines to finish quickly
          group: 'all tests' # name this group "all tests" on the dashboard
          start: 'npm start' # start server before running tests

      - heroku/deploy-via-git:
        requires:
          - cypres/run
        filters:
          branches:
            only: main